DROP TABLE IF EXISTS ODONTOLOGOS;
CREATE TABLE ODONTOLOGOS (ID LONG AUTO_INCREMENT PRIMARY KEY, NUMERO_MATRICULA LONG NOT NULL, NOMBRE VARCHAR(50) NOT NULL, APELLIDO VARCHAR(50) NOT NULL);

INSERT INTO ODONTOLOGOS(NUMERO_MATRICULA, NOMBRE, APELLIDO) VALUES (123456, 'Luis', 'Soto');

INSERT INTO ODONTOLOGOS(NUMERO_MATRICULA, NOMBRE, APELLIDO) VALUES (654321, 'Daniel', 'Chacon');

DROP TABLE IF EXISTS DOMICILIOS;
CREATE TABLE DOMICILIOS (ID LONG AUTO_INCREMENT PRIMARY KEY, CALLE VARCHAR(50) NOT NULL, NUMERO INT NOT NULL, LOCALIDAD VARCHAR(50) NOT NULL, PROVINCIA VARCHAR(50));

INSERT INTO DOMICILIOS (CALLE, NUMERO, LOCALIDAD, PROVINCIA) VALUES ('Estanislao Lopez', 4514, 'Malvin', 'Montevideo');

DROP TABLE IF EXISTS PACIENTES;
CREATE TABLE PACIENTES (ID LONG AUTO_INCREMENT PRIMARY KEY, DNI LONG NOT NULL, NOMBRE VARCHAR(50) NOT NULL, APELLIDO VARCHAR(50) NOT NULL, DOMICILIO INT, FECHA_ALTA DATE);

INSERT INTO PACIENTES (DNI, NOMBRE, APELLIDO,DOMICILIO, FECHA_ALTA) VALUES (98765432, 'Ana', 'Perez', 1, '2024-05-24');

INSERT INTO PACIENTES (DNI, NOMBRE, APELLIDO, DOMICILIO, FECHA_ALTA) VALUES (87654321, 'Juan', 'Gomez', 1, '2024-05-23');

DROP TABLE IF EXISTS TURNOS;
CREATE TABLE TURNOS (ID LONG AUTO_INCREMENT PRIMARY KEY, FECHA_Y_HORA TIMESTAMP, ODONTOLOGO INT NOT NULL, PACIENTE INT NOT NULL);

